[WIP] Inter Vehicular Communication
Santara/MADRaS pull request #10
Opened 2019-12-22 17:39 UTC by rudrasohan

What?
- Incorporated MMDP action_space into observations
- Created an action_buffer with custom_history_size for different agents. 
- Implemented a connection map for specifying agents relationships.

Testing:
 - `python test_environment_v2.py`
- Set `multi_flag` true for turning on communications for that particular agent.
- Set `buff_size` which specifies the history size for a particular agent.
- `com_info` is a dict which contains the different agents and the actions_spaces and history_sizes. It also contains communication_map.

2020-02-29 08:21 UTC, rudrasohan commented
Updates:
- Removed conflicting names.
- Added agent wait in reset.
- Fixed bugs due to multiprocessing.
- Training Possible in multi setting.

2020-03-05 06:34 UTC, Santara reviewed
## Overall comments:
Well organized code. Currently the IV comm system only supports::
1. Action communicaton
2. Bidirectional communication among all the agents that choose to communicate

It would be great if we could generalize the construction to include the communication of observations and arbitrary communication graphs.

2020-03-05 06:34 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +madras = md.MadrasDatatypes()
The nomenclature of this variable is confusing. I would suggest something like `madras_datatypes = md.MadrasDatatypes()`

2020-03-05 06:34 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +                additional_dims += dims*self.observation['size']
Lets generalize it to any observed or action variable.

2020-03-05 06:34 UTC, Santara commented on MADRaS/utils/action_buffer.py
> +class ActionBuffer:
Lets make it a general variable buffer

2020-03-05 06:34 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +                    self.comm_info[agent_name] = self.agents[name].action_dim
It might  be a good idea to make action dim a keyed entity within the `self.comm_info[agent_name]` dictionary. Concretely, I would prefer a construct like the following:
`self.comm_info[agent_name]['action_dim'] = self.agents[name].action_dim`

2020-03-05 06:34 UTC, Santara commented on MADRaS/utils/action_buffer.py
> +        To hold the last k actions of taken
no "of"

2020-03-05 06:34 UTC, Santara commented on MADRaS/utils/action_buffer.py
> +        self._curr_size = 0
maybe rename it `self._num_elements`?

2020-03-05 06:34 UTC, Santara commented on MADRaS/utils/action_buffer.py
> +    def request(self):
You should ideally have an argument (optional) `num_elements` to be able to request all or some of the elements in the buffer.

2020-03-05 06:34 UTC, Santara commented on MADRaS/utils/action_buffer.py
> +            ret[i*self._action_dim: (i+1)*self._action_dim] = a
Isn't using a Queue for this application is an overkill? You could do the same with a simple list :) You need not serialize and deserialize the data...

2020-03-05 06:34 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
>                  name = '{}_{}'.format(agent_name, i)
the co-existence of the variables: `agent_name` and `name` is confusing. Consider renaming one of them.

2020-03-05 06:34 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +                        self.comm_info["agent_map"][agent].append(comm_agent)
Currently the IV-COMM logic is as follows:
Suppose you have four MadrasAgents. Agent 1 has `multi_flag = False`. The remaining three agents have `multi_flag = True`. In this case, 2 will comm with 3 and 4, 3 with 2 and 4 and 4 with 2 and 3. This is a bidirectional fully connected comm graph among the communicating agents. 

What if, we want 2 to comm with just 3, 3 with 4 and 4 with 2. This is a cyclic relationship. Can we make the IV-COMM protocol generic enough to support  any kind of communication relationship?

2020-03-12 07:21 UTC, rudrasohan commented
Sorry for the delay.
I'll be finishing it off by Monday.

2020-03-14 05:00 UTC, rudrasohan commented on MADRaS/envs/gym_madras_v2.py
> +madras = md.MadrasDatatypes()
The `madras_datatypes` is the name of the datatypes file. I was thinking of using a small abbreviation like `np`. In the next pr, I'll be changing it to `mt` (abbreviation for madras types).

2020-03-18 05:31 UTC, rudrasohan commented
Updated Changes:
- Generalized buffer for any variable
- Code cleaning
- Custom Communication Architecture

New additions:
- `communications.yml`
- a new flag `init_wait` in `sim_opions` for custom wait times at the beginning of the episode.

How to configure communications:
```yml
MadrasAgent_0:
    buff_size: 2
    vars:
        - action
        - speedX
        - speedY
        - track
    comms:
        - MadrasAgent_1
        - MadrasAgent_0


MadrasAgent_1:
    buff_size: 2
    vars:
        - action
        - speedX
        - speedY
        - trackPos
        - opponents
    comms:
        - MadrasAgent_0

```

For each agent `buff_size` indicates the buffer size, `vars` are the variables that you want from the other agents and `comms` are the agents whose data you require. The architecture resembles a directed graph `A -> B != B -> A`. 

Testing:

`python test_environment_v2.py`

2020-04-02 13:24 UTC, Santara reviewed
Wonderful work!

1. Does it make practical sense to have different `buffer_size` for different agents? If agent_1 wants history of previous 2 time steps and agent_2 has `buffer_size=1`, what does it supply for the last-but-one time step?
2. Rename `sim_options_v2.yml` to `madras_config_v2.yml`?

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +                additional_dims += 1
Repeated condition.

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
`var` is not supposed to be a list, right? So `var== 'speed'` should have been appropriate.

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +        additional_dims_h = []
instead of `additional_dims_h`, maybe `additional_vars_high` would have been more approriate, because, the sub-string `dims` makes the variable look scalar.

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +                #     self.comm_info["agent"][name] = (self.agents[name].action_dim, self.agents[name].buff_size)
Remove comment if not used.

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
Remove comments if not in use

2020-04-02 13:24 UTC, Santara commented on MADRaS/utils/observation_handler.py
>              full_obs = self.normalize_obs(full_obs, game_config)
We should get rid of the `self.normalize_obs` function as it doesn't serve any useful purpose right now. In that case we dont have to return the input `full_obs`

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
>          # self.action_dim = self.agents[0].action_dim  # TODO(santara): Can I not have different action dims for different agents?
Remove comments if not used later in the PR

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +        #     self.agents[agent].action_buffer.insert(action[agent])
remove

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +        #         next_obs[agent] = np.hstack((next_obs[agent], self.agents[comm_agents].action_buffer.request()))
remove unnecessary comments

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +        #         s_t[agent] = np.hstack((s_t[agent], self.agents[comm_agents].comms_buffer.request()))
unnecessary comments

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +        #print("FULL OBS {}".format(full_obs._asdict()))
maybe you want  to use `logging.info` and keep these uncommented

2020-04-02 13:24 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +        #import pdb; pdb.set_trace()
removve

2020-04-02 13:24 UTC, Santara commented on MADRaS/utils/communications_buffer.py
> +        #print("BUFFER_SIZE {}".format(buffer_array.shape))
put these in `logging.info` so that we can only print these in logging level `debug`?

2020-04-03 14:51 UTC, rudrasohan commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
It's done to simultaneously handle `speedX`, `speedY` and `speedZ` with a single line.

2020-04-03 14:53 UTC, rudrasohan commented on MADRaS/envs/gym_madras_v2.py
> +                additional_dims += 1
This is probably an old file. Otdated written here.

2020-04-03 14:54 UTC, rudrasohan commented on MADRaS/envs/gym_madras_v2.py
> +        additional_dims_h = []
Sure, will change it.

2020-04-03 15:05 UTC, rudrasohan commented on MADRaS/utils/observation_handler.py
>              full_obs = self.normalize_obs(full_obs, game_config)
Let's keep it for the time being. I will make it a bit more fleshed out with different types of normalizations in a later PR.

2020-04-04 06:46 UTC, Santara requested changes
Just a few more nit-picky comments :)

Can you walk me through your code for IV-COMM one last time before we check in?

Thanks!

2020-04-04 06:46 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
This is smart! Could you please add a comment to explain it :)

2020-04-04 06:46 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
Remove commented lines 262-267.

2020-04-04 06:46 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
In line 398-399, why do we need to hardcode to `MadrasAgent_0`? The user might want to name their learning agents in some other way.

2020-04-04 06:46 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
In line 499, replace unused `next_reward`, `next_done` and `nexxt_info` variables with `_`. In line 498, replace `i` with `_`.

2020-04-04 06:46 UTC, Santara commented on MADRaS/envs/gym_madras_v2.py
> +            elif ('speed' in var):
In `communications.yml`, why does `MadrasAgent_0` appear in the `comms` list for `MadrasAgent_0`? I see that this is overlooked in the code and `MadrasAgent_0`  and `MadrasAgent_1` happen to have the same `obs_dim`.

2020-04-05 10:04 UTC, rudrasohan commented
Tested and checked.

2020-04-19 10:05 UTC, Santara commented
Could you remove `max_episode_steps` and `reward_threshold` from the register command in __init__.py of the root directory?

2020-04-19 15:12 UTC, rudrasohan commented
Updated with the requested changes.

2020-04-19 15:21 UTC, merged